### ISSUE TITLE
Unable to run parcel-app

### ISSUE THREAD

**Issue by tifosiblack** [karttofer/quick-parcel-app#2]
Hello and thanks for your project,

I tried to create a parcel app to test, but I get an error when I run the npx parcel-app command :

`
--------:WebstormProjects ------$ npx parcel-app test
npx: installed 74 in 4.397s

    Creating a new project in: ./test
			
    Creating a packpage.json...
    Getting neccesary dependencies. This can take a few minutes.
      
  ✖ Building Folder
    Building package
    Gettings Dependencies...
(node:57019) UnhandledPromiseRejectionWarning: [object Array]
(node:57019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I don't know where it comes from, but here's my node env :

`
--------:WebstormProjects ------$ npm --version
6.9.0

--------:WebstormProjects ------$ node --version
v10.16.3
`

**Comment by karttofer** [comment]
Thanks so much for you support!

Try fist running 
1. npm i parcel-app -g
2. parcel-app my-project

This is an issue that I'm triying to fix, please let me know if this works for you

**Comment by tifosiblack** [comment]
I tried what you proposed, I get the same result.
I'm on MacOs, maybe it change something.

**Comment by tifosiblack** [comment]
It works on my windows installation, I don't really know why.

**Comment by karttofer** [comment]
Ooh, meybe it could be an error in Mac os. Sorry for this laaate answer I was very busy. I think that it could be for the commands. I will try to fix it

**Comment by karttofer** [comment]
Hi - Person that I don't know, this issue finally was fixed hahahaha. Have a good life!

**Comment by karttofer** [comment]
Finally fixed, testes in MacOS and Windows

**Comment by tifosiblack** [comment]
> Hi - Person that I don't know, this issue finally was fixed hahahaha. Have a good life!

I didn't remember anymore this issue but thanks 👍
